### ISSUE TITLE
P02 Geometry creating gcode file in the gigabytes

### ISSUE THREAD

**Issue by fneuk** [Shahak-Kuba/Melt-ElectroCoder-Application#1]
Hello,

I only started using you App so maybe it's a mistake on my part but:

OS: Windows 10
Matlab: R2024a

Melt ElectroCoder settings:
![grafik](https://github.com/user-attachments/assets/a4f990a3-8925-4665-baec-beb3a4a77c59)

With this settings, a gcode file is created (still not finished while I wrote this issue) of 4.5 GBs:

![grafik](https://github.com/user-attachments/assets/58c8c5a8-80f3-4b8c-95bd-592ebb540d5d)

Thanks for you work!

**Comment by Shahak-Kuba** [comment]
Hi,

Just wanted to confirm that you were after a scaffold that was 30 mm x 30 mm with individual cells that are 2 um (micrometers) x 8 um? In that case, those cell sizes are quite small for a scaffold print that is in millimetres, which would give you quite a large file size.

Thanks

**Comment by fneuk** [comment]
My bad, should have looked at "Repeating Cells" to see that this would lead to too much cells and therefore a big file size.

But now I have another question. Let's say the scaffold stays the same (30 x 30 mm) and Geometry is P02 and the build "p & q" (as in my original post).

(1) p = 2 and q = 8 gives me:
![grafik](https://github.com/user-attachments/assets/87058e7d-0615-4d66-989c-749bd6e16d61)
3000 repeating cells (x and y)

(2) p = 20 and q = 80 gives me:
![grafik](https://github.com/user-attachments/assets/5c525b7a-8dd0-4764-b9a4-d6cae67bec6a)
300.000 repeating cells (x and y)

and (3) p = 200 and q = 800 gives me:
![grafik](https://github.com/user-attachments/assets/77f0c995-8aed-4f9d-8fc5-8e74f07e50f4)
30.000 repeating cells (x and y)

Is there something wrong with the display of repeating cells in (1)? Shouldn't this be more than (2) and (3)?

edit:
Oh, the point is a decimal point and not a thousand separator. So its (1) 3000, (2) 300 and (3) 30.
